export const Profile=[
    {
        id:1,
        name:"Mario Speedwagon",
        standard:"9",
        Language:"JavaScript",
        CodingLvl :"5 star ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ",
        email:"mario@gmail.com",
    },
    {
        id:2,
        name:"Petey Cruiser",
        standard:"7",
        Language:"JavaScript",
        CodingLvl :"4 star ⭐️ ⭐️ ⭐️ ⭐️ ",
        email:"petey@gmail.com",
    },{
        id:3,
        name:"Anna Sthesia",
        standard:"12",
        Language:"Python",
        CodingLvl :"3 star ⭐️ ⭐️ ⭐️  ",
        email:"anna@gmail.com",
    },{
        id:4,
        name:"Paul Molive",
        standard:"11",
        Language:"C",
        CodingLvl :"4 star ⭐️ ⭐️ ⭐️ ⭐️ ",
        email:"paul@gmail.com",
    },
    {
        id:5,
        name:"Gail Forcewind",
        standard:"10",
        Language:"C++",
        CodingLvl :"1 star ⭐️",
        email:"gail@gmail.com",
    },
    {
        id:6,
        name:"Barb Dwyer",
        standard:"8",
        Language:"Python",
        CodingLvl :"4 star ⭐️ ⭐️ ⭐️ ⭐️ ",
        email:"barb@gmail.com",
    },
    {
        id:7,
        name:"Moe Fugga",
        standard:"8",
        Language:"C",
        CodingLvl :"2 star ⭐️ ⭐️ ",
        email:"moe@gmail.com",
    },
    {
        id:8,
        name:"Tom Foolery",
        standard:"10",
        Language:"Java",
        CodingLvl :"4 star ⭐️ ⭐️ ⭐️ ⭐️ ",
        email:"tom@gmail.com",
    },
    {
        id:9,
        name:"Arty Ficial",
        standard:"11",
        Language:"c",
        CodingLvl :"1 star ⭐️ ",
        email:"arty@gmail.com",
    },
    {
        id:10,
        name:"Tara Misu",
        standard:"9",
        Language:"JavaScript",
        CodingLvl :"5 star ⭐️ ⭐️ ⭐️ ⭐️ ",
        email:"tara@gmail.com",
    },

]